name: musicfinder2
description: A new Flutter project.
version: 0.0.1
#author: Asanda Ndimande <asandax6@gmail.com>
homepage: https://www.github.com/Asandax6/musicfinder2

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.12.0 <2.0.0"


dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^0.5.8

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.asanda.musicfinder2
        pluginClass: MusicfinderPlugin
      ios:
        pluginClass: MusicfinderPlugin